name: blackjack
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2020.10.14
  - certifi=2020.11.8
  - openssl=1.1.1h
  - pip=20.2.4
  - python=3.7.9
  - setuptools=50.3.1
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - brotli==1.0.9
    - chardet==3.0.4
    - click==7.1.2
    - colorlog==4.6.2
    - cycler==0.10.0
    - dash==1.17.0
    - dash-core-components==1.13.0
    - dash-html-components==1.1.1
    - dash-renderer==1.8.3
    - dash-table==4.11.0
    - flask==1.1.2
    - flask-compress==1.8.0
    - future==0.18.2
    - idna==2.10
    - itsdangerous==1.1.0
    - jinja2==2.11.2
    - kiwisolver==1.3.1
    - markupsafe==1.1.1
    - matplotlib==3.3.3
    - numpy==1.19.4
    - pandas==1.1.4
    - pillow==8.0.1
    - plotly==4.13.0
    - pyorbital==1.6.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2020.4
    - pyyaml==5.3.1
    - requests==2.25.0
    - retrying==1.3.3
    - scipy==1.5.4
    - six==1.15.0
    - urllib3==1.26.2
    - werkzeug==1.0.1
prefix: /home/scott/anaconda3/envs/blackjack
